- block:
    - name: Obtain SSO token
      ovirt_auth:
          url: "{{ vars['dr_sites_' + dr_source_map + '_url'] }}"
          username: "{{ vars['dr_sites_' + dr_source_map + '_username'] }}"
          password: "{{ vars['dr_sites_' + dr_source_map + '_password'] }}"
          ca_file: "{{ vars['dr_sites_' + dr_source_map + '_ca_file'] }}"

    - include_tasks: tasks/clean/shutdown_vms.yml storage={{ item }}
      with_items:
          - "{{ dr_import_storages }}"
      loop_control:
          loop_var: storage

    - include_tasks: tasks/clean/update_ovf_store.yml storage={{ item }}
      with_items:
          - "{{ dr_import_storages }}"
      loop_control:
          loop_var: storage

    - name: Set force remove flag to false for non master domains
      set_fact: dr_force=False

    - name: Set query for remove valid non master domains
      # TODO: Filter only data and iso types
      set_fact: dr_query_domain_search='status = active and type != cinder or status = maintenance and type != cinder or status = unattached and type != glance and type != cinder'

    - name: Set master storage domain filter
      set_fact: only_master=False

    - include_tasks: tasks/clean/remove_filtered_master_domains.yml storage={{ item }}
      with_items:
          - "{{ dr_import_storages }}"
      loop_control:
          loop_var: storage

    # We use inactive filter only at the end, since we are not sure if there were any storage domains
    # which became inactive on the process or if there were any on the beginning.
    - name: Set force remove flag to true for non master domains
      set_fact: dr_force=True

    - name: Set query for remove invalid non master domains
      # TODO: Filter only data and iso types
      set_fact: dr_query_domain_search='type != glance and type != cinder and status != active'

    - include_tasks: tasks/clean/remove_filtered_master_domains.yml storage={{ item }}
      with_items:
          - "{{ dr_import_storages }}"
      loop_control:
          loop_var: storage

    - name: Set query for remove valid master domains
      # TODO: Filter only data and iso types
      set_fact: dr_query_domain_search='type != cinder and status = active or type != glance and type != cinder and status = maintenance'

    - name: Set master storage domain filter
      set_fact: only_master=True

    - name: Set force remove flag to false for master domain
      set_fact: dr_force=False

    - include_tasks: tasks/clean/remove_filtered_master_domains.yml storage={{ item }}
      with_items:
          - "{{ dr_import_storages }}"
      loop_control:
          loop_var: storage

    - name: Set force remove flag to true for master domain
      set_fact: dr_force=True

    # If by any chance we got storage domains which are inactive we force remove them.
    - name: Set query for remove invalid master domains
      # TODO: Filter only data and iso types
      set_fact: dr_query_domain_search='type != glance and type != cinder and status != active'

    - include_tasks: tasks/clean/remove_filtered_master_domains.yml storage={{ item }}
      with_items:
          - "{{ dr_import_storages }}"
      loop_control:
          loop_var: storage

    - name: Fetch leftover storage domains
      ovirt_storage_domains_facts:
          pattern: type != glance
          auth: "{{ ovirt_auth }}"

    # TODO: Document that behavior
    # Remove VMs only if there are no data storage domains left in the setup
    - name: Fetch leftover VMs in the setup
      ovirt_vms_facts:
          pattern: status = down
          auth: "{{ ovirt_auth }}"
      when: dr_clean_orphaned_vms and ovirt_storage_domains | length == 0

    - include_tasks: tasks/clean/remove_vms.yml vm={{ item }}
      with_items: "{{ ovirt_vms }}"
      when: dr_clean_orphaned_vms and ovirt_storage_domains | length == 0

    # Remove direct LUN disks
    - name: Fetch leftover direct LUN disks in the setup
      ovirt_disk_facts:
          pattern: disk_type = lun and number_of_vms =0
          auth: "{{ ovirt_auth }}"
      when: dr_clean_orphaned_disks and ovirt_storage_domains | length == 0

    - include_tasks: tasks/clean/remove_disks.yml disk={{ item }}
      with_items: "{{ ovirt_disks }}"
      when: dr_clean_orphaned_disks and ovirt_storage_domains | length == 0


  # Default value is set in role defaults
  ignore_errors: "{{ dr_ignore_error_clean }}"
  tags:
      - fail_back
      - clean_engine

- always:
    - name: Revoke the SSO token
      ovirt_auth:
          state: absent
          ovirt_auth: "{{ ovirt_auth }}"

