- block:
    - name: Fetch active/maintenance/detached storage domain for remove
      ovirt_storage_domains_facts:
          pattern:  name={{ storage['dr_' + dr_source_map + '_name'] }} and datacenter={{ storage['dr_' + dr_source_map + '_dc_name'] }} and {{ dr_active_domain_search }} or
                    name={{ storage['dr_' + dr_source_map + '_name'] }} and datacenter={{ storage['dr_' + dr_source_map + '_dc_name'] }} and {{ dr_maintenance_domain_search }} or
                    name={{ storage['dr_' + dr_source_map + '_name'] }} and {{ dr_unattached_domain_search }}
          auth: "{{ ovirt_auth }}"

    - name: Remove valid storage domain
      include_tasks: tasks/clean/remove_domain_process.yml sd={{ sd }}
      with_items:
          - "{{ ovirt_storage_domains }}"
      when: (not only_master and not sd.master) or (only_master and sd.master)
      loop_control:
          loop_var: sd
  ignore_errors: "{{ dr_ignore_error_clean }}"
  tags:
      - fail_back
      - clean_engine
