- name: Import FCP storage domain
  ovirt_storage_domains:
      state: imported
      id: "{{ fcp_storage['dr_domain_id'] }}"
      name: "{{ fcp_storage['dr_' + dr_target_host + '_name']|default('') }}"
      host: "{{ ovirt_hosts[0].name }}"
      auth: "{{ ovirt_auth }}"
      data_center: "{{ fcp_storage['dr_' + dr_target_host + '_dc_name'] }}"
      fcp: {}
